services:
  - type: web
    name: ga-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GA_PROPERTY_ID
        description: "Your Google Analytics 4 Property ID (e.g., 123456789)"
        required: true
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        description: "Your Google Service Account JSON credentials (as a single line)"
        required: true
        isSecret: true
 